create database UPSC

use UPSC

SELECT * FROM UPSC_DATASET 

UPDATE UPSC_DATASET 
SET 
MAINS_ESSAY = COALESCE(Mains_Essay, 0),
GS_PAPER_1 = COALESCE(GS_PAPER_1, 0),
GS_PAPER_2 = COALESCE(GS_PAPER_2, 0),
GS_PAPER_3 = COALESCE(GS_PAPER_3, 0),
GS_PAPER_4 = COALESCE(GS_PAPER_4, 0),
OPTIONAL_1 = COALESCE(OPTIONAL_1, 0),
OPTIONAL_2 = COALESCE(OPTIONAL_2, 0),
INTERVIEW_CALL = COALESCE(INTERVIEW_CALL, 'FALSE'),
INTERVIEW_MARKS = COALESCE(INTERVIEW_MARKS, 0),
FINAL_RANK = COALESCE(FINAL_RANK, 0);

CREATE VIEW SERVICE_BENCHMARK AS
SELECT SERVICE_ALLOCATED, 
COUNT(*) AS [TOTAL SELECTIONS],
AVG(AVERAGE_DAILY_STUDY_HOURS) AS [AVERAGE STUDY HOURS PER DAY],
AVG(TOTAL_MAINS) AS [AVERAGE MAINS MARKS],
AVG(INTERVIEW_MARKS) AS [AVERAGE INTERVIEW MARKS],
AVG(FINAL_TOTAL) AS [AVERAGE FINAL MARKS]
FROM UPSC_DATASET
WHERE SERVICE_ALLOCATED != 'NOT RECOMMENDED'
GROUP BY SERVICE_ALLOCATED; 

SELECT * FROM SERVICE_BENCHMARK ORDER BY [AVERAGE FINAL MARKS] DESC;

CREATE OR ALTER VIEW UPSC_FUNNEL AS
SELECT *,
CASE WHEN SERVICE_ALLOCATED != 'NOT RECOMMENDED' THEN '4. ALLOCATED'
WHEN INTERVIEW_CALL = 'TRUE' THEN '3. INTERVIEW CALL'
WHEN PASSED_PRELIMS = 'TRUE' THEN '2. PASSED PRELIMS'
ELSE '1. TOTAL APPLICANTS' END AS [STAGE] FROM UPSC_DATASET